global:
  scrape_interval: 5s  # metric rate

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # metric path
    static_configs:
      - targets: ['localhost:8081']  # app

  - job_name: 'node-exporter'  # server monitoring (CPU, RAM)
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert.rules.yml"
